# ===========================
# Server
# ===========================
server.port=8080

# ===========================
# PostgreSQL
# ===========================
spring.datasource.url=jdbc:postgresql://localhost:5432/flashcart_db
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# ===========================
# JPA
# ===========================
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ===========================
# Flyway
# ===========================
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# ===========================
# Redis
# ===========================
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.username=default
spring.data.redis.password=flashcart_redis_pass
spring.data.redis.timeout=2000ms
spring.cache.type=redis
spring.cache.redis.time-to-live=300000

# ===========================
# JWT
# ===========================
app.jwt.secret=5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
app.jwt.expiration-ms=86400000

# ===========================
# Flash Sale Config
# ===========================
app.sale.reservation-hold-seconds=120
app.sale.max-quantity-per-user=3
app.rate-limit.requests-per-minute=30

# ===========================
# Swagger
# ===========================
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# ===========================
# Logging
# ===========================
logging.level.com.flashcart=DEBUG
